### PR TITLE
Russian localization

### PR DESCRIPTION
**Pull request by iStyx**
Adds Russian localization.

### CODE REVIEW

**Comment by dteviot** [comment]
@iStyx  - Thank you

**Comment by iStyx** [comment]
@dteviot Ukrainian localization is on its way as well :)

**Comment by dteviot** [comment]
@iStyx When is it likely to be done?  If it's a few days, I'll hold off from updating the version in the store until then.  If it's a couple of weeks, I'll update the version in the store immediately.

**Comment by iStyx** [comment]
@dteviot I'll make a PR tomorrow, so if you'd hold off updating store version until then that would be great.

**Comment by dteviot** [comment]
@iStyx  Will do.

**Pull request merged**
