### PR TITLE
Add web.archive.org support

### PR DESCRIPTION
**Pull request by belldandu**
This pull request is to add the enhancement at https://github.com/dteviot/WebToEpub/issues/2

### CODE REVIEW

**Comment by belldandu** [comment]
Yeah i forgot about that e.e its fixed now.

**Comment by belldandu** [comment]
As far as i know by design your supposed to get the height and width While the image loads. I also tested this and all the images dimensions are set properly. However i can also parse the data listed on the html page to get the size if you still wan't to avoid taking any chances.

**Comment by dteviot** [comment]
I think there's a mis-communication here.
I have trouble seeing how you can get the dimensions while loading is in
progress,  Until you have the file you don't know how big it is.

Here's my thoughts.
1. I'm happy with the WebArchive and the image removal bug fixes.
2. Fetching the large scale image.  Not so much.  I personally prefer the
scaled down images.  (Although I'm now suspecting most people want the full
scale images.)

So, I'd accept 1, and 2 I want' to think about a bit.

**Comment by belldandu** [comment]
@dteviot 
I could do this but even this could have potential issues.
```
    let span = util.getElement(div, "span");
    var img = span.innerHTML.split("(")[1];
    if(img){
        img = img.split(" pixels,")[0].split(" x ");
        imageInfo.height = img[0].replace(",", "")
        imageInfo.width = img[1].replace(",", "");
    }
```

Also as for your one question https://davidwalsh.name/get-image-dimensions 
This has been around for a long time. Everything in onload is called imediatly after the image is loaded.

**Comment by dteviot** [comment]
> Everything in onload is called imediatly after the image is loaded.

That's what I understood.
However, onLoad is only called when the image is loaded.  Which occurs some time in the future.  Until onLoad is called the height and width values of imageInfo are not valid.  So if the main thread tries to read imageInfo before onLoad is called, the values will be wrong.  I.e. need to wait until onLoad is called.  See http://www.html5rocks.com/en/tutorials/es6/promises/, then look at function BakaTsukiImageCollector.prototype.fetchImages.

**Comment by dteviot** [comment]
i.e. I think updateImageInfoFromImagePage needs to return a promise that is resolved when onLoad finishes.

Please fogive me, I need to go away and do some thinking.

**Comment by belldandu** [comment]
Thats why i put the return inside of onload.

In your promise, then cannot be called until after ```that.updateImageInfoFromImagePage(rawDom, imageInfo);``` has returned something.

By placing the return inside of onload you keep the integrity of the values as nothing is returned until after the image has been fully loaded.

At least thats how it should do and has done so far. I can even try limiting the connection in the browser and test to make sure its still working.

**Comment by belldandu** [comment]
And ok

**Comment by belldandu** [comment]
Ok yeah just tested definetly needs a promise.

**Comment by belldandu** [comment]
There we go it now is promised and i tested it to. Works perfectly even when throttled to 50kbps with 500ms ping. @dteviot

**Comment by dteviot** [comment]
Thanks.  
On quick glance, looks OK.
I'm afraid it's getting late for me, and I need to go to sleep.
Will probably merge tomorrow.

**Comment by belldandu** [comment]
Awesome. and night

**Comment by belldandu** [comment]
@dteviot o.o

**Comment by dteviot** [comment]
I've merged it into the current dev branch "Sonako" and will send updated build 0.0.0.4 to Chrome Webstore.  If I hear no complaints in a few days, will merge to trunk.

**Comment by belldandu** [comment]
Ok

**Comment by belldandu** [comment]
Ignore those last 2

**Comment by dteviot** [comment]
> Confused as to how de40496 managed to be slightly different from 09dbe2c Did you edit it afterwards?

Yes.  Got merge conflicts and had to fix.
Took liberty to make some minor tweaks.

**Comment by belldandu** [comment]
Awesome.

**Comment by belldandu** [comment]
I'm moving onto the next pull request to fix https://github.com/dteviot/WebToEpub/issues/4
Feel free to make tweaks.

**Pull request closed without merging**
