### PR TITLE
Add additional metadata to template parser

### PR DESCRIPTION
**Pull request by gamebeaker**
I had a few problems with GitHub that's why so many commits. The last one contains all.
Help require to save user check boxes preferences "no Additional Metadata" and "less tags".
Is it a problem that it is forked from my master branch? It seems like i can't push my local changes to my experimentaltabmode branch. Every time i get 'Authentication failed. Some common reasons include:'...

### CODE REVIEW

**Comment by Emasoft** [comment]
Great, let's hope this is going to be merged soon. 
Just a note:
Currently this code export only basic metadata, like a single author, but for Light Novels the authors are usually 2: the writer and the illustrator. Both are equally important for catalogueing and searching epubs. 
For the correct syntax, please look at the "contributor" field tagged as "ill" (illustrator role) from this real world example of the epub output:

```xml
<dc:identifier id="book-id" opf:scheme="ISBN">1234567890X</dc:identifier> 
    <dc:title id="english">Battle Through the Heavens</dc:title>
    <meta refines="#english" property="title-type">english title</meta>
    <dc:title id="original">斗破苍穹</dc:title>
    <meta refines="#original" property="title-type">original title</meta>
    <dc:title id="alternative">Fights Break Sphere</dc:title>
    <meta refines="#alternative" property="title-type">alternative title</meta>
     <dc:language id="text-language">en</dc:language>
    <meta refines="#text-language" property="identifier-type" scheme="onix:codelist22">01</meta>
    <dc:language id="original-language">cn</dc:language>
    <meta refines="#original-language" property="identifier-type" scheme="onix:codelist22">02</meta>
    <dc:creator opf:role="aut" >Heavenly Silkworm Potato</dc:creator>
    <dc:creator opf:role="aut" >Tian Can Tu Dou</dc:creator>
    <dc:creator opf:role="aut" >天蚕土豆</dc:creator>
    <dc:creator opf:role="trl" >GravityTales</dc:creator>
    <dc:contributor opf:role="ill" >Hongbin Zhou</dc:contributor>
    <dc:publisher>Qidian</dc:publisher>
    <dc:subject>Action</dc:subject>
    <dc:subject>Adventure</dc:subject>
    <dc:subject>Fantasy</dc:subject>
    <dc:subject>Harem</dc:subject>
    <dc:subject>Martial Arts</dc:subject>
    <dc:subject>Xuanhuan</dc:subject>
    <dc:date opf:event="publication">2018-01-01T00:00:00Z</dc:date>
    <dc:source>urn:isbn:1234567890X</dc:source>
    <dc:description>"In a land where no magic is present. A land where the strong make the rules and the weak have to obey. A land filled with alluring treasures and beauty, yet also filled with unforeseen danger. Three years ago, Xiao Yan, who had shown talents none had seen in decades, suddenly lost everything. His powers, his reputation, and his promise to his mother. What sorcery has caused him to lose all of his powers? And why has his fiancee suddenly shown up? </dc:description>
 <link href="https://www.novelupdates.com/series/battle-through-the-heavens/" />
  </metadata> 
```

Also there are other things missing, like alternative titles, author alternative names and original language, but those are less important than the illustrator.

**Comment by gamebeaker** [comment]
@Emasoft i use calibre and can't view 'ill' or 'trl' in the metadata section. Can you recommend a epub viewer wich could show all metadata?

**Comment by Emasoft** [comment]
> @Emasoft i use calibre and can't view 'ill' or 'trl' in the metadata section. Can you recommend a epub viewer wich could show all metadata?

You should try Sigil:

https://publishdrive.com/managing-metadata-within-book.html

**Comment by dteviot** [comment]
@gamebeaker 
1. I note there's still a mixture of tabs an spaces for indentation, and inconconsistent indentation as well.  e.g. Changes to Template.js
I'm going to assume you're not running eslint before submitting.  If your are, please check you're using the same settings I am.

2. In order to have a setting saved, add an entry to UserPreferences constructor in file UserPreferences.js.  Look at commit https://github.com/dteviot/WebToEpub/commit/ed56871215234210eab6c9c383f453bc9576630b#diff-7c5868a895b279c63bc6fd4bb346193795a1554435e9bdf735fc648ae0027be6)

3. Instead of submitting a pull request with multiple commits, It would be better to consolidate them into a single commit.  It makes it a lot easier for me to review what you've done.
I believe the way you're supposed to do this is "squash" commits.
Google suggests this is the process to use: https://medium.com/@mittalyashu/how-to-squash-commits-in-a-github-pull-request-97b36576eacb

**Comment by dteviot** [comment]
@gamebeaker
Just to be clear, I'm asking you to please fix items 1 and 3 of my previous note, before I accept this pull request.
You might also like to do 2 as well, as I think it's a one line code change.

If you've already done this, I apologize, I don't seem to have received a notification that it was done.

**Comment by gamebeaker** [comment]
@dteviot no need to apologize it is just that i have exams next week so i have no time. 
Before i submit the next i will fix 1 and 3 but it will take a few weeks i think.

**Comment by dteviot** [comment]
@gamebeaker
No problem.  Whenever and whatever you can is fine, and greatly appreciated.

**Pull request closed without merging**
