### PR TITLE
new parser for German Gutenberg Projekt

### PR DESCRIPTION
**Pull request by GallusMax**
my poor contribution to this great tool.. adding epub functionality to license free german books

### CODE REVIEW

**Comment by dteviot** [comment]
Thanks very much for the contribution.
However, I'd like a couple of changes made before I accept it.
1. Change name of class from TemplateParser.  I'd suggest GutenbergDEParser.  You'll need to update lines 10 and 22.
2. Remove the comments (and commented out code from the template.

**Comment by GallusMax** [comment]
sorry, I obvioulsy missed that.
There are still some gutenbergDE books, that will not produce an epub. I will fix this in another PR.

**Comment by GallusMax** [comment]
that was fun. The fix extracts Author and Title even for those books that do not come with a frontpage with clean metadata. please include as well! Thanks again for the shoulder to stand on! :-)

**Comment by dteviot** [comment]
@GallusMax
> Thanks again for the shoulder to stand on! :-)

You are very welcome.  The whole point of providing the template was to allow others to contribute.
Minor note, I forgot to run eslint over the code before accepting it.  There were issues with formatting and some unreachable code which I've fixed.  But you might like to double check.  I've also uploaded new version to Chrome store, and submitted to Mozilla.

**Pull request merged**
