### PR TITLE
fixed literotica.com

### PR DESCRIPTION
**Pull request by yoanhg421**
Added capability to pull from Top Lists and Categories.
Fixed selectors for article list and series page.

### CODE REVIEW

**Comment by dteviot** [comment]
@yoanhg421 I appreciate your efforts.  However, you've reformatted the files, which makes it difficult to see the changes you've intentionally made, versus the reformatting.  Please restore the original formatting.

**Comment by gamebeaker** [comment]
@yoanhg421 if you run the command: "npm run lint" you should get a lot of errors/warnings like: "Expected indentation of 4 spaces but found 2" etc.

**Comment by yoanhg421** [comment]
@dteviot 
I ran lint with the --fix but it didn't really do anything, al least not to my files. I'm guessing it did it on the packed extension.
My vscode formats the file automatically everytime I save. I'll try to figure something out. 
You are right, I can't even tell what I changed anymore LOL. But I know it's working. 
I'll fix it. 

Quick question. Is there a function call the gets the Author? I didn't see it in the original file and it keeps saying <unkwown> on the export

**Comment by dteviot** [comment]
@yoanhg421 
> Is there a function call the gets the Author?

https://github.com/dteviot/WebToEpub/blob/master/plugin/js/parsers/Template.js#L63-L74

**Comment by yoanhg421** [comment]
@dteviot Thank you. Author and Title are looking better now. 
I pushed the fixes. I thinks it should be good now. 
I wasn't really sure how to revert the changes but I think it worked. Git is not my strong suit.

**Comment by dteviot** [comment]
@yoanhg421 
That looks better.  Please note, due to RL issues, it might be a couple of weeks before I'm able to fully inspect and merge.

**Comment by dteviot** [comment]
@yoanhg421 
Thanks.
For future reference, please merge to ExperimentalTabMode branch, not master. 
ExperimentalTabMode is the dev branch.  Master is for tracking most recently released.  (i.e. It's the "stable" branch)

**Comment by dteviot** [comment]
For my notes: 40 minutes work.

**Pull request merged**
