### PR TITLE
Firefox Support with WebExtensions

### PR DESCRIPTION
**Pull request by Gusser93**
Pull request to add the enhancement #6

### CODE REVIEW

**Comment by belldandu** [comment]
Man that was fast. Nice to see other people contributing :D

**Comment by dteviot** [comment]
Thanks very much for doing this.
However:
1. The readme needs to indicate that the extension works for both Chrome and Firefox.  (Assuming the change to the download also works for Chrome.)
2. I suggest the id in the manifest.json be WebToEpub@Baka-tsuki.org
3. You should add a minimum Firefox version.

**Comment by belldandu** [comment]
> Thanks very much for doing this.
> However:
> 1. The readme needs to indicate that the extension works for both Chrome and Firefox. (Assuming the change to the download also works for Chrome.)
> 2. I suggest the id in the manifest.json be WebToEpub@Baka-tsuki.org
> 3. You should add a minimum Firefox version.

agree with 1 and 2.

Your initial readme is perfect but you should make that old readme be merged with the current one.

For 3 firefox nightly is required

**Comment by dteviot** [comment]
@Gusser93 
Thanks very much for this contribution, 
I'd like to merge it in so that you can have credit.
However, I'd also like to get a Firefox version available as soon as possible.
So, can you please fix the readme issue so I can merge?

If I don't hear from you in 2 days, I'm going to cherry pick the fix for the download.

**Comment by Gusser93** [comment]
@dteviot
I hope now is everything fine. Feel free to edit as much as needed. Did a little test on Canary and it worked.

**Comment by belldandu** [comment]
LGTM

**Comment by dteviot** [comment]
Looks good.  Currently at work, but will merge later today when I have time.
Thanks muchly.

**Pull request merged**
