### PR TITLE
Qq xenforo migration

### PR DESCRIPTION
**Pull request by Kiradien**
QuestionableQuesting has switched over to Xenforo, this is a basic functional transition logic with basic testing. Images may have issues depending on modifications.

### CODE REVIEW

**Comment by Kiradien** [comment]
Ironic failure; "irregular whitespace" or NBSP (160) is actually generated by tag-prefixes in XenForo, and was put in the code as a in a regex replacement to underscore. Will switch to &nbsp; & see if that works.

**Comment by dteviot** [comment]
@Kiradien 
Thank you very much.  
FYI, in future, please squash into single commit.
While I can do it, it makes it easier for me to inspect the changes.

**Comment by dteviot** [comment]
@Kiradien 
Your change to util.safeForFileName did not work.  And broke unit tests.
I have fixed. See: https://github.com/dteviot/WebToEpub/commit/4d5c4b91cefbee425d32e22edb7b79c5a84ee44f

**Comment by Kiradien** [comment]
> @Kiradien Your change to util.safeForFileName did not work. And broke unit tests. I have fixed. See: [4d5c4b9](https://github.com/dteviot/WebToEpub/commit/4d5c4b91cefbee425d32e22edb7b79c5a84ee44f)

Thanks; not exactly sure how that happened, my local code/branch is a single pipe.



> @Kiradien Thank you very much. FYI, in future, please squash into single commit. While I can do it, it makes it easier for me to inspect the changes.

Sorry about that; I did try, but git was being stubborn about merging my squashed changes into my main branch && wouldnt accept a forced push - [77aef50](https://github.com/dteviot/WebToEpub/pull/1305/commits/77aef50d6ab0565bde61c4bdbb2492531987d7c2) was supposed to be the squashed changeset.

**Pull request merged**
