### PR TITLE
update lightnovelworldparser

### PR DESCRIPTION
**Pull request by gamebeaker**
remove new watermark/ markers from lightnovelworld.com
#475

### CODE REVIEW

**Comment by dteviot** [comment]
@gamebeaker 
Thanks very much for attempting to fix this issue.
However, I think https://github.com/dteviot/WebToEpub/commit/9a185bc16bdeb8277510d774db5fdd38f0486faf is a better way of doing it.

**Comment by gamebeaker** [comment]
@dteviot  In "autosearch additional metadata/ add additional metadata on template" i added an autosearch function for additional metadata i am listing the changes following:
.eslint.js : "ecmaVersion": 8->2019 because i got an error with try{}catch{} and here  https://github.com/eslint/eslint/issues/13838 they suggested using 2019.
i added the possibility to the parser template to add additional metadata from the website directly.
the user input (checkboxes) is saved.
in the second pull i made the lightnovelworld filter better.
In Madara and roaylroad parser i have to disable eslint for a few lines because they need to be ' not "

**Comment by dteviot** [comment]
@gamebeaker
I'm not sure what you're asking from me.
My suggestion is, make your change on your repo version, commit, and send me a note.
Or, if you want to discuss anything, crate an issue on your repo and again, mention my name @dteviot 
I should get back to you within 24 hours, depending on how busy I am.

**Comment by gamebeaker** [comment]
@dteviot i thought i committed new changes shortly after you have seen the old and so have overseen the additional changes i made.

**Comment by dteviot** [comment]
@gamebeaker 
I've just received a new commit and would like to do a release, so the version in the Chrome and Firefox stores can be updated.
However, when I do a release, it takes weeks to get it approved by Google, and I can't do another until Google finishes their assessment.
So, is it likely that you'll have your PR ready in within a few days?
Note, I'm not asking you to hurry.  It's just it it's likely to be ready in a few days, I'll hold off doing a release until it's merged.
If it won't be ready, that's fine, just be aware that I won't be able to publish it to the Google and Firefox stores for at least a couple of weeks.  

Well, I could publish to Firefox store,, they usually approve in less than an hour, but I like to keep the versions synchronized.

**Comment by gamebeaker** [comment]
@dteviot Hi in CONTRIBUTING.md is the point.
Do all existing unit tests pass?
If i run unitTest/Test.html i get 15 failed even if i haven't changed anything is this normal or do i something wrong?
I open this HTML in Chrome 88.0.4324.190 (64-Bit)
image

**Comment by dteviot** [comment]
@gamebeaker 
My bad, I haven't run the unit tests under Chrome for some time.  (The need to close all running instances and reconfigure is a pain, So I always run them under Firefox.  Note, you can install multiple copies of Firefox,  e.g. the Normal and Developer versions, and I configure the Developer version so unit tests run.  And then use it just for running unit tests.)
Obviously, something has rotted and I'll need to investigate and fix.  (Probably another config setting.)

If the tests pass under Firefox, go ahead and commit.

**Pull request closed without merging**
