### PR TITLE
lightnovelworld.com changed to lightnovelpub.com

### PR DESCRIPTION
**Pull request by gamebeaker**
Added lightnovelpub.com to lightnovelworld parser. #485

### CODE REVIEW

**Comment by dteviot** [comment]
@gamebeaker 
Thanks. I do appreciate the effort.  But I'm going to decline it.
Basically, I accept a pull there's an hour of work on my side to sync everything up.
For a one line change like this, It's much less work for me to just add the one line change myself.

Incidentally, while I have you
1. You might like to have a look at https://github.com/dteviot/WebToEpub/commit/f5d5799b42388255a19a4ae445dde054837e4b7e for how to solve that eslint warning
2. I'm wondering why you wrote this
```javascript
let tags = [...dom.querySelector("div .genres-content").querySelectorAll("[rel='tag']")];
```

instead of
```javascript
let tags = [...dom.querySelectorAll("div .genres-content [rel='tag']")];
```

**Comment by gamebeaker** [comment]
@dteviot I wrote let tags = [...dom.querySelector("div .genres-content").querySelectorAll('[rel="tag"]')]; first and after i got eslint errors which was like use " for Strings not ' i tried ("[rel="tag"]") and it didn't worked i didn't knew you have to swap them to ("[rel='tag']") to work that is why i decided to disable eslint. Could you please change this in the template to. I made there the same mistake but it isn't shown in eslint because it is a comment.

**Comment by dteviot** [comment]
@gamebeaker 
I figured that's what you'd done for the eslint error.  
I was more interested in why querySelector() followed by querySelectorAll()?

And I'll fix the template.

**Comment by gamebeaker** [comment]
@dteviot My thought process was like ok i now have my html box with div and .genres-content and now i want to have all genre with rel=tag from inside this box i simple didn't thought of using only one querySelectorAll() with all statements together. I am pretty new to js, html, programming... maybe that's the reason why i simple haven't fought of solving the problem more efficient and easier.
Thanks for pointing this out. I appreciate it.

**Pull request closed without merging**
