### PR TITLE
Better Readme

### PR DESCRIPTION
**Pull request by Dimava**
I'm going to try to make better readme somehow

### CODE REVIEW

**Comment by Dimava** [comment]
bot

**Comment by Dimava** [comment]
🤔 

Well, I now have a video, and I can add it to readme
Will it look good tho?

**Comment by Dimava** [comment]
> Note, I usually put copies of the current Development versions
Please, try the scrips I wrote (`npm run release pre draft`) for keeping binaries on github

**Comment by dteviot** [comment]
Thanks for your efforts, I've updated the instructions.

**Pull request closed without merging**
