### PR TITLE
feat: readme update

### PR DESCRIPTION
**Pull request by Jemeni11**
Major overhaul of the README file.

### CODE REVIEW

**Comment by dteviot** [comment]
I appreciate your work. 

There's some inaccuracies/issues/out of date stuff, but I'm not sure if I just accept as is, and then fix, or if you're willing to fix before I merge.

The most notable is that I'm pretty sure you built the list of supported sites from the names of the parsers.  Unfortunately:
1. Names don't always match.  (Sites have changed their name.)
2. The list is not exhaustive.  A number of the parsers handle multiple sites.  e.g. Madara. Mtlnation
3. Not all of the files are for a site.  e.g. Template.js is an example for building a parser.  WordpressBase is used to build parsers for Wordpress hosted sites.
4. Some of the parsers are there simply so WebToEpub can tell user the site ISN'T supported.  eg. BabelChain

Maintaining this list going forward is also going to be extra work.  That said, I think we can get away with changing "Full list of Supported Sites" to "Last we checked, the following sites were known to work."  And don't bother with a count.  It's another item to maintain and will drift out of sync.

"Built With" section is misleading.
HTML, CSS and JS.  are languages shown on the main page.  So, don't need to be repeated here.
I'd suggest section should be 
**Build With**
- Node.js
- eslint

**Libraries Used (in WebToEpub)
- jszip

**Libraries used by WebToEpub build process**
- @xmldom/xmldom
- copyfiles
- quint

Links to dteviot.github.io should be replaced with equivalent links to https://github.com/dteviot/WebToEpub/wiki.  (the io site is not being maintained.)

The "Contributors (40)", I'd remove the count.  It's another thing to rember to update and keep in sync

Version of JSZip in license is out of date.  It should be "3.7.1", not "3.0.0"

**Comment by gamebeaker** [comment]
>The most notable is that I'm pretty sure you built the list of supported sites from the names of the parsers.  Unfortunately:
>1. Names don't always match.  (Sites have changed their name.)
>2. The list is not exhaustive.  A number of the parsers handle multiple sites.  e.g. Madara. Mtlnation
>3. Not all of the files are for a site.  e.g. Template.js is an example for building a parser.  WordpressBase is used to build parsers for Wordpress hosted sites.
>4. Some of the parsers are there simply so WebToEpub can tell user the site ISN'T supported.  eg. BabelChain

with `console.log(parserFactory);` you can get a list of links for which specific parser exist.
The list is not accurate as discussed here: #1414
Here is a list extracted from parserFactory missing are the 7 generic parser.
```
Wordpress
Baka-Tsuki Full Text Page
Baka-Tsuki Series Page
Blogspot
Default
NovelNext
WLPublishing
Wikipedia
```
all links `console.log([...parserFactory.parsers.keys()].sort());`
<details>
  <summary>Full list of Supported Sites (447)</summary>
<ul>
<li>230book.net</li>
<li>38xs.com</li>
<li>4ksw.com</li>
<li>888novel.com</li>
<li>88xiaoshuo.net</li>
<li>8muses.com</li>
<li>a-t.nu</li>
<li>aerialrain.com</li>
<li>akknovel.com</li>
<li>all-novelfull.net</li>
<li>allnovel.org</li>
<li>allnovelbin.net</li>
<li>allnovelbook.com</li>
<li>allnovelfull.app</li>
<li>allnovelfull.com</li>
<li>allnovelfull.net</li>
<li>allnovelfull.org</li>
<li>allnovelnext.com</li>
<li>alphapolis.co.jp</li>
<li>alternatehistory.com</li>
<li>amor-yaoi.com</li>
<li>anythingnovel.com</li>
<li>arcanetranslations.com</li>
<li>archiveofourown.org</li>
<li>asianfanfics.com</li>
<li>asianhobbyist.com</li>
<li>asianovel.net</li>
<li>asstr.org</li>
<li>babelnovel.com</li>
<li>baka-tsuki.org</li>
<li>bakapervert.wordpress.com</li>
<li>bednovel.com</li>
<li>bestlightnovel.com</li>
<li>betwixtedbutterfly.com</li>
<li>bnatranslations.com</li>
<li>book18.org</li>
<li>bookalb.com</li>
<li>bookswithqianya.com</li>
<li>botitranslation.com</li>
<li>boxnovel.net</li>
<li>boxnovel.org</li>
<li>boxnovelfull.com</li>
<li>boylove.cc</li>
<li>bqka.cc</li>
<li>cangji.net</li>
<li>cclawtranslations.home.blog</li>
<li>chaleuria.com</li>
<li>chichipeph.com</li>
<li>chickengege.org</li>
<li>chinesewuxia.world</li>
<li>chrysanthemumgarden.com</li>
<li>chyoa.com</li>
<li>ckandawrites.online</li>
<li>comics.8muses.com</li>
<li>comrademao.com</li>
<li>coronatranslation.com</li>
<li>creativenovels.com</li>
<li>crimsonmagic.me</li>
<li>crimsontranslations.com</li>
<li>cyborg-tl.com</li>
<li>czbooks.net</li>
<li>daotranslate.com</li>
<li>daotranslate.us</li>
<li>dark-novels.ru</li>
<li>deviantart.com</li>
<li>dummynovels.com</li>
<li>edanglarstranslations.com</li>
<li>engnovel.com</li>
<li>erofus.com</li>
<li>exiledrebelsscanlations.com</li>
<li>faloomtl.com</li>
<li>fanfiction.com.br</li>
<li>fanfiction.mugglenet.com</li>
<li>fanfiction.net</li>
<li>fanmtl.com</li>
<li>fannovel.com</li>
<li>fannovels.com</li>
<li>fansmtl.com</li>
<li>fastnovel.net</li>
<li>ffxs8.com</li>
<li>fictionhunt.com</li>
<li>fictionmania.tv</li>
<li>fictionpress.com</li>
<li>fictionzone.net</li>
<li>ficwad.com</li>
<li>fimfiction.net</li>
<li>finestories.com</li>
<li>flying-lines.com</li>
<li>forum.questionablequesting.com</li>
<li>forums.nrvnqsr.com</li>
<li>forums.spacebattles.com</li>
<li>forums.sufficientvelocity.com</li>
<li>foxteller.com</li>
<li>freelightnovel.net</li>
<li>freenovelsread.com</li>
<li>freewebnovel.com</li>
<li>freewn.com</li>
<li>frostfire10.wordpress.com</li>
<li>fullnovel.co</li>
<li>gamefaqs.gamespot.com</li>
<li>genesistls.com</li>
<li>genesistudio.com</li>
<li>goblinsguide.com</li>
<li>graverobbertl.site</li>
<li>gravitynovels.com</li>
<li>gravitytales.com</li>
<li>gunnerkrigg.com</li>
<li>gutenberg.spiegel.de</li>
<li>helheimscans.com</li>
<li>hellping.org</li>
<li>hentai-foundry.com</li>
<li>hiscension.com</li>
<li>hostednovel.com</li>
<li>hoxionia.com</li>
<li>hui3r.wordpress.com</li>
<li>idleturtle-translations.com</li>
<li>idnovel.my.id</li>
<li>imgur.com</li>
<li>indomtl.com</li>
<li>indowebnovel.id</li>
<li>inkitt.com</li>
<li>innnovel.com</li>
<li>inoveltranslation.com</li>
<li>isekaicyborg.wordpress.com</li>
<li>isekaiscan.com</li>
<li>isotls.com</li>
<li>jade-rabbit.net</li>
<li>japtem.com</li>
<li>jjwxc.net</li>
<li>jobnib.com</li>
<li>jonaxxstories.com</li>
<li>jpmtl.com</li>
<li>kakuyomu.jp</li>
<li>kaystls.site</li>
<li>kemono.su</li>
<li>knoxt.space</li>
<li>kobatochan.com</li>
<li>krytykal.org</li>
<li>lazygirltranslations.com</li>
<li>liberspark.com</li>
<li>libread.com</li>
<li>libri7.com</li>
<li>lightnovelbastion.com</li>
<li>lightnovelbox.com</li>
<li>lightnovelcave.com</li>
<li>lightnovelfr.com</li>
<li>lightnovelpub.com</li>
<li>lightnovelpub.fan</li>
<li>lightnovelread.com</li>
<li>lightnovelreader.org</li>
<li>lightnovels.live</li>
<li>lightnovels.me</li>
<li>lightnovelstranslations.com</li>
<li>lightnovelworld.co</li>
<li>lightnovelworld.com</li>
<li>lightsnovel.com</li>
<li>listnovel.com</li>
<li>literotica.com</li>
<li>lnmtl.com</li>
<li>lnreader.org</li>
<li>m.88xiaoshuo.net</li>
<li>m.bqg225.com</li>
<li>m.chinesefantasynovels.com</li>
<li>m.freelightnovel.net</li>
<li>m.gzbpi.com</li>
<li>m.metanovel.org</li>
<li>m.mywuxiaworld.com</li>
<li>m.novelspread.com</li>
<li>m.qqxs.vip</li>
<li>m.tapas.io</li>
<li>m.wuxiaworld.co</li>
<li>m.xklxsw.net</li>
<li>machine-translation.org</li>
<li>madnovel.com</li>
<li>magic.wizards.com</li>
<li>mandarinducktales.com</li>
<li>mangabob.com</li>
<li>mangadex.org</li>
<li>mangahere.cc</li>
<li>mangakakalot.com</li>
<li>mangallama.com</li>
<li>manganelo.com</li>
<li>manganov.com</li>
<li>mangaread.co</li>
<li>mangasushi.net</li>
<li>manhwaden.com</li>
<li>manhwatop.com</li>
<li>marx2mao.com</li>
<li>mayanovel.com</li>
<li>mcstories.com</li>
<li>meionovel.id</li>
<li>midnightrambles.in</li>
<li>moonbunnycafe.com</li>
<li>moonlightnovel.com</li>
<li>moonquill.com</li>
<li>morenovel.net</li>
<li>mtlarchive.com</li>
<li>mtled-novels.com</li>
<li>mtlnation.com</li>
<li>mtlnovel.com</li>
<li>mtlreader.com</li>
<li>mtnovel.net</li>
<li>myxls.net</li>
<li>nanomashin.online</li>
<li>ncode.syosetu.com</li>
<li>nightcomic.com</li>
<li>noblemtl.com</li>
<li>novel-bin.com</li>
<li>novel-bin.net</li>
<li>novel-bin.org</li>
<li>novel-next.com</li>
<li>novel.babelchain.org</li>
<li>novel.naver.com</li>
<li>novel18.syosetu.com</li>
<li>novel35.com</li>
<li>novelactive.org</li>
<li>novelall.com</li>
<li>novelbin.com</li>
<li>novelbin.me</li>
<li>novelbin.net</li>
<li>novelbuddy.com</li>
<li>novelbuddy.io</li>
<li>novelcool.com</li>
<li>novelcranel.org</li>
<li>novelcrush.com</li>
<li>novelebook.net</li>
<li>novelfever.com</li>
<li>novelfire.docsachhay.net</li>
<li>novelfull.com</li>
<li>novelfull.net</li>
<li>novelfullbook.com</li>
<li>novelgate.net</li>
<li>novelgo.id</li>
<li>novelgreat.net</li>
<li>novelhall.com</li>
<li>novelhi.com</li>
<li>novelhold.com</li>
<li>novelhulk.net</li>
<li>novellive.app</li>
<li>novellive.com</li>
<li>novellive.net</li>
<li>novelmania.com.br</li>
<li>novelmao.com</li>
<li>novelmax.net</li>
<li>novelmedium.com</li>
<li>novelmt.com</li>
<li>novelmtl.com</li>
<li>novelnext.com</li>
<li>novelnext.dramanovels.io</li>
<li>novelnext.net</li>
<li>novelnextz.com</li>
<li>novelonlinefree.com</li>
<li>novelonlinefree.info</li>
<li>novelonlinefull.com</li>
<li>novelonomicon.com</li>
<li>novelpassion.com</li>
<li>novelplex.org</li>
<li>novelpub.com</li>
<li>novels.pl</li>
<li>novelsect.com</li>
<li>novelsemperor.com</li>
<li>novelsemperor.net</li>
<li>novelsknight.com</li>
<li>novelsparadise.net</li>
<li>novelspread.com</li>
<li>novelsrock.com</li>
<li>noveltoon.mobi</li>
<li>noveltop1.org</li>
<li>noveltranslatedbyc.blogspot.com</li>
<li>noveltrench.com</li>
<li>noveltrust.net</li>
<li>noveluniverse.com</li>
<li>novelupdates.cc</li>
<li>novelupdates.online</li>
<li>novelusb.com</li>
<li>novelusb.net</li>
<li>novelversetranslations.com</li>
<li>novelxo.net</li>
<li>novicetranslations.com</li>
<li>ntruyen.vn</li>
<li>nyantl.wordpress.com</li>
<li>octopii.co</li>
<li>onlinenovelbook.com</li>
<li>ontimestory.eu</li>
<li>ossantl.com</li>
<li>panda-novel.com</li>
<li>pandamtl.com</li>
<li>pandapama.com</li>
<li>pandasnovel.com</li>
<li>patreon.com</li>
<li>pawread.com</li>
<li>peachblossomcodex.com</li>
<li>peachpitting.com</li>
<li>peachpuff.in</li>
<li>pery.info</li>
<li>piaotia.com</li>
<li>puretl.com</li>
<li>qinxiaoshuo.com</li>
<li>quanben.io</li>
<li>quanben5.io</li>
<li>questionablequesting.com</li>
<li>quotev.com</li>
<li>raeitranslations.com</li>
<li>rainingtl.org</li>
<li>rainofsnow.com</li>
<li>raisingthedead.ninja</li>
<li>ranobes.net</li>
<li>ranobes.top</li>
<li>re-library.com</li>
<li>readcomiconline.li</li>
<li>reader-hub.com</li>
<li>readfreebooksonline.org</li>
<li>readhive.org</li>
<li>readlightnovel.cc</li>
<li>readlightnovel.me</li>
<li>readlightnovel.meme</li>
<li>readlightnovel.org</li>
<li>readlightnovel.today</li>
<li>readlitenovel.com</li>
<li>readnoveldaily.com</li>
<li>readnovelfull.com</li>
<li>readnovelfull.me</li>
<li>readnovelfull.org</li>
<li>readwebnovel.xyz</li>
<li>readwn.com</li>
<li>readwn.org</li>
<li>rebirth.online</li>
<li>reddit.com</li>
<li>royalroad.com</li>
<li>royalroadl.com</li>
<li>rtd.moe</li>
<li>rtenzo.net</li>
<li>rubymaybetranslations.com</li>
<li>scifistories.com</li>
<li>scribblehub.com</li>
<li>secondlifetranslations.com</li>
<li>semprot.com</li>
<li>sexstories.com</li>
<li>shalvationtranslations.wordpress.com</li>
<li>shanghaifantasy.com</li>
<li>shikkakutranslations.org</li>
<li>shinsori.com</li>
<li>shintranslations.com</li>
<li>shirokuns.com</li>
<li>shmtranslations.com</li>
<li>shubaow.net</li>
<li>shubaowb.com</li>
<li>shw5.cc</li>
<li>sites.google.com</li>
<li>sj.uukanshu.com</li>
<li>sjks88.com</li>
<li>skydemonorder.com</li>
<li>skythewoodtl.com</li>
<li>snowycodex.com</li>
<li>sonako.fandom.com</li>
<li>sonako.wikia.com</li>
<li>sousetsuka.com</li>
<li>soverse.com</li>
<li>spiritfanfiction.com</li>
<li>sspai.com</li>
<li>starlightstream.net</li>
<li>sto.cx</li>
<li>storiesonline.net</li>
<li>storyseedling.com</li>
<li>sweek.com</li>
<li>systemtranslation.com</li>
<li>taffygirl13.wordpress.com</li>
<li>tamagotl.com</li>
<li>taonovel.com</li>
<li>tapas.io</li>
<li>tapread.com</li>
<li>teanovel.com</li>
<li>teanovel.net</li>
<li>teenfic.net</li>
<li>thenovelbin.org</li>
<li>tigertranslations.org</li>
<li>timotxt.com</li>
<li>titannovel.net</li>
<li>tl.rulate.ru</li>
<li>tomotranslations.com</li>
<li>topnovelfull.com</li>
<li>translationchicken.com</li>
<li>travistranslations.com</li>
<li>truyenfull.vn</li>
<li>truyenyy.com</li>
<li>trxs.me</li>
<li>ultimaguil.org</li>
<li>universalnovel.com</li>
<li>unlimitednovelfailures.mangamatters.com</li>
<li>untamedalley.com</li>
<li>veratales.com</li>
<li>vipnovel.com</li>
<li>volarenovels.com</li>
<li>wanderertl130.id</li>
<li>wanderinginn.com</li>
<li>watashiwasugoidesu.com</li>
<li>wattpad.com</li>
<li>webnovel.com</li>
<li>webnovel.live</li>
<li>webnovelonline.com</li>
<li>webnovelpub.com</li>
<li>webnovelpub.pro</li>
<li>wenku8.net</li>
<li>wfxs.tw</li>
<li>whitemoonlightnovels.com</li>
<li>wnmtl.com</li>
<li>wnmtl.org</li>
<li>woopread.com</li>
<li>wordexcerpt.com</li>
<li>worldnovel.online</li>
<li>wtr-lab.com</li>
<li>wuxia-world.online</li>
<li>wuxia.blog</li>
<li>wuxia.city</li>
<li>wuxia.click</li>
<li>wuxiabee.com</li>
<li>wuxiabee.net</li>
<li>wuxiabee.org</li>
<li>wuxiafox.com</li>
<li>wuxiago.com</li>
<li>wuxiahere.com</li>
<li>wuxiahub.com</li>
<li>wuxiamtl.com</li>
<li>wuxiaone.com</li>
<li>wuxiap.com</li>
<li>wuxiapub.com</li>
<li>wuxiar.com</li>
<li>wuxiaspot.com</li>
<li>wuxiau.com</li>
<li>wuxiaworld.co</li>
<li>wuxiaworld.com</li>
<li>wuxiaworld.eu</li>
<li>wuxiaworld.live</li>
<li>wuxiaworld.online</li>
<li>wuxiaworld.site</li>
<li>wuxiaworld.world</li>
<li>wuxiazone.com</li>
<li>xbiquge.so</li>
<li>xiaoshuogui.com</li>
<li>xiaxuenovels.xyz</li>
<li>yoraikun.wordpress.com</li>
<li>yushubo.net</li>
<li>zenithnovels.com</li>
<li>zeonic-republic.net</li>
<li>zhenhunxiaoshuo.com</li>
<li>zinnovel.net</li>
<li>zirusmusings.com</li>
</ul>
</details>

<details>
  <summary>markdown code for "Full list of Supported Sites (447)"</summary>  

  ```html
<details>
  <summary>Full list of Supported Sites (447)</summary>
<ul>
<li>230book.net</li>
<li>38xs.com</li>
<li>4ksw.com</li>
<li>888novel.com</li>
<li>88xiaoshuo.net</li>
<li>8muses.com</li>
<li>a-t.nu</li>
<li>aerialrain.com</li>
<li>akknovel.com</li>
<li>all-novelfull.net</li>
<li>allnovel.org</li>
<li>allnovelbin.net</li>
<li>allnovelbook.com</li>
<li>allnovelfull.app</li>
<li>allnovelfull.com</li>
<li>allnovelfull.net</li>
<li>allnovelfull.org</li>
<li>allnovelnext.com</li>
<li>alphapolis.co.jp</li>
<li>alternatehistory.com</li>
<li>amor-yaoi.com</li>
<li>anythingnovel.com</li>
<li>arcanetranslations.com</li>
<li>archiveofourown.org</li>
<li>asianfanfics.com</li>
<li>asianhobbyist.com</li>
<li>asianovel.net</li>
<li>asstr.org</li>
<li>babelnovel.com</li>
<li>baka-tsuki.org</li>
<li>bakapervert.wordpress.com</li>
<li>bednovel.com</li>
<li>bestlightnovel.com</li>
<li>betwixtedbutterfly.com</li>
<li>bnatranslations.com</li>
<li>book18.org</li>
<li>bookalb.com</li>
<li>bookswithqianya.com</li>
<li>botitranslation.com</li>
<li>boxnovel.net</li>
<li>boxnovel.org</li>
<li>boxnovelfull.com</li>
<li>boylove.cc</li>
<li>bqka.cc</li>
<li>cangji.net</li>
<li>cclawtranslations.home.blog</li>
<li>chaleuria.com</li>
<li>chichipeph.com</li>
<li>chickengege.org</li>
<li>chinesewuxia.world</li>
<li>chrysanthemumgarden.com</li>
<li>chyoa.com</li>
<li>ckandawrites.online</li>
<li>comics.8muses.com</li>
<li>comrademao.com</li>
<li>coronatranslation.com</li>
<li>creativenovels.com</li>
<li>crimsonmagic.me</li>
<li>crimsontranslations.com</li>
<li>cyborg-tl.com</li>
<li>czbooks.net</li>
<li>daotranslate.com</li>
<li>daotranslate.us</li>
<li>dark-novels.ru</li>
<li>deviantart.com</li>
<li>dummynovels.com</li>
<li>edanglarstranslations.com</li>
<li>engnovel.com</li>
<li>erofus.com</li>
<li>exiledrebelsscanlations.com</li>
<li>faloomtl.com</li>
<li>fanfiction.com.br</li>
<li>fanfiction.mugglenet.com</li>
<li>fanfiction.net</li>
<li>fanmtl.com</li>
<li>fannovel.com</li>
<li>fannovels.com</li>
<li>fansmtl.com</li>
<li>fastnovel.net</li>
<li>ffxs8.com</li>
<li>fictionhunt.com</li>
<li>fictionmania.tv</li>
<li>fictionpress.com</li>
<li>fictionzone.net</li>
<li>ficwad.com</li>
<li>fimfiction.net</li>
<li>finestories.com</li>
<li>flying-lines.com</li>
<li>forum.questionablequesting.com</li>
<li>forums.nrvnqsr.com</li>
<li>forums.spacebattles.com</li>
<li>forums.sufficientvelocity.com</li>
<li>foxteller.com</li>
<li>freelightnovel.net</li>
<li>freenovelsread.com</li>
<li>freewebnovel.com</li>
<li>freewn.com</li>
<li>frostfire10.wordpress.com</li>
<li>fullnovel.co</li>
<li>gamefaqs.gamespot.com</li>
<li>genesistls.com</li>
<li>genesistudio.com</li>
<li>goblinsguide.com</li>
<li>graverobbertl.site</li>
<li>gravitynovels.com</li>
<li>gravitytales.com</li>
<li>gunnerkrigg.com</li>
<li>gutenberg.spiegel.de</li>
<li>helheimscans.com</li>
<li>hellping.org</li>
<li>hentai-foundry.com</li>
<li>hiscension.com</li>
<li>hostednovel.com</li>
<li>hoxionia.com</li>
<li>hui3r.wordpress.com</li>
<li>idleturtle-translations.com</li>
<li>idnovel.my.id</li>
<li>imgur.com</li>
<li>indomtl.com</li>
<li>indowebnovel.id</li>
<li>inkitt.com</li>
<li>innnovel.com</li>
<li>inoveltranslation.com</li>
<li>isekaicyborg.wordpress.com</li>
<li>isekaiscan.com</li>
<li>isotls.com</li>
<li>jade-rabbit.net</li>
<li>japtem.com</li>
<li>jjwxc.net</li>
<li>jobnib.com</li>
<li>jonaxxstories.com</li>
<li>jpmtl.com</li>
<li>kakuyomu.jp</li>
<li>kaystls.site</li>
<li>kemono.su</li>
<li>knoxt.space</li>
<li>kobatochan.com</li>
<li>krytykal.org</li>
<li>lazygirltranslations.com</li>
<li>liberspark.com</li>
<li>libread.com</li>
<li>libri7.com</li>
<li>lightnovelbastion.com</li>
<li>lightnovelbox.com</li>
<li>lightnovelcave.com</li>
<li>lightnovelfr.com</li>
<li>lightnovelpub.com</li>
<li>lightnovelpub.fan</li>
<li>lightnovelread.com</li>
<li>lightnovelreader.org</li>
<li>lightnovels.live</li>
<li>lightnovels.me</li>
<li>lightnovelstranslations.com</li>
<li>lightnovelworld.co</li>
<li>lightnovelworld.com</li>
<li>lightsnovel.com</li>
<li>listnovel.com</li>
<li>literotica.com</li>
<li>lnmtl.com</li>
<li>lnreader.org</li>
<li>m.88xiaoshuo.net</li>
<li>m.bqg225.com</li>
<li>m.chinesefantasynovels.com</li>
<li>m.freelightnovel.net</li>
<li>m.gzbpi.com</li>
<li>m.metanovel.org</li>
<li>m.mywuxiaworld.com</li>
<li>m.novelspread.com</li>
<li>m.qqxs.vip</li>
<li>m.tapas.io</li>
<li>m.wuxiaworld.co</li>
<li>m.xklxsw.net</li>
<li>machine-translation.org</li>
<li>madnovel.com</li>
<li>magic.wizards.com</li>
<li>mandarinducktales.com</li>
<li>mangabob.com</li>
<li>mangadex.org</li>
<li>mangahere.cc</li>
<li>mangakakalot.com</li>
<li>mangallama.com</li>
<li>manganelo.com</li>
<li>manganov.com</li>
<li>mangaread.co</li>
<li>mangasushi.net</li>
<li>manhwaden.com</li>
<li>manhwatop.com</li>
<li>marx2mao.com</li>
<li>mayanovel.com</li>
<li>mcstories.com</li>
<li>meionovel.id</li>
<li>midnightrambles.in</li>
<li>moonbunnycafe.com</li>
<li>moonlightnovel.com</li>
<li>moonquill.com</li>
<li>morenovel.net</li>
<li>mtlarchive.com</li>
<li>mtled-novels.com</li>
<li>mtlnation.com</li>
<li>mtlnovel.com</li>
<li>mtlreader.com</li>
<li>mtnovel.net</li>
<li>myxls.net</li>
<li>nanomashin.online</li>
<li>ncode.syosetu.com</li>
<li>nightcomic.com</li>
<li>noblemtl.com</li>
<li>novel-bin.com</li>
<li>novel-bin.net</li>
<li>novel-bin.org</li>
<li>novel-next.com</li>
<li>novel.babelchain.org</li>
<li>novel.naver.com</li>
<li>novel18.syosetu.com</li>
<li>novel35.com</li>
<li>novelactive.org</li>
<li>novelall.com</li>
<li>novelbin.com</li>
<li>novelbin.me</li>
<li>novelbin.net</li>
<li>novelbuddy.com</li>
<li>novelbuddy.io</li>
<li>novelcool.com</li>
<li>novelcranel.org</li>
<li>novelcrush.com</li>
<li>novelebook.net</li>
<li>novelfever.com</li>
<li>novelfire.docsachhay.net</li>
<li>novelfull.com</li>
<li>novelfull.net</li>
<li>novelfullbook.com</li>
<li>novelgate.net</li>
<li>novelgo.id</li>
<li>novelgreat.net</li>
<li>novelhall.com</li>
<li>novelhi.com</li>
<li>novelhold.com</li>
<li>novelhulk.net</li>
<li>novellive.app</li>
<li>novellive.com</li>
<li>novellive.net</li>
<li>novelmania.com.br</li>
<li>novelmao.com</li>
<li>novelmax.net</li>
<li>novelmedium.com</li>
<li>novelmt.com</li>
<li>novelmtl.com</li>
<li>novelnext.com</li>
<li>novelnext.dramanovels.io</li>
<li>novelnext.net</li>
<li>novelnextz.com</li>
<li>novelonlinefree.com</li>
<li>novelonlinefree.info</li>
<li>novelonlinefull.com</li>
<li>novelonomicon.com</li>
<li>novelpassion.com</li>
<li>novelplex.org</li>
<li>novelpub.com</li>
<li>novels.pl</li>
<li>novelsect.com</li>
<li>novelsemperor.com</li>
<li>novelsemperor.net</li>
<li>novelsknight.com</li>
<li>novelsparadise.net</li>
<li>novelspread.com</li>
<li>novelsrock.com</li>
<li>noveltoon.mobi</li>
<li>noveltop1.org</li>
<li>noveltranslatedbyc.blogspot.com</li>
<li>noveltrench.com</li>
<li>noveltrust.net</li>
<li>noveluniverse.com</li>
<li>novelupdates.cc</li>
<li>novelupdates.online</li>
<li>novelusb.com</li>
<li>novelusb.net</li>
<li>novelversetranslations.com</li>
<li>novelxo.net</li>
<li>novicetranslations.com</li>
<li>ntruyen.vn</li>
<li>nyantl.wordpress.com</li>
<li>octopii.co</li>
<li>onlinenovelbook.com</li>
<li>ontimestory.eu</li>
<li>ossantl.com</li>
<li>panda-novel.com</li>
<li>pandamtl.com</li>
<li>pandapama.com</li>
<li>pandasnovel.com</li>
<li>patreon.com</li>
<li>pawread.com</li>
<li>peachblossomcodex.com</li>
<li>peachpitting.com</li>
<li>peachpuff.in</li>
<li>pery.info</li>
<li>piaotia.com</li>
<li>puretl.com</li>
<li>qinxiaoshuo.com</li>
<li>quanben.io</li>
<li>quanben5.io</li>
<li>questionablequesting.com</li>
<li>quotev.com</li>
<li>raeitranslations.com</li>
<li>rainingtl.org</li>
<li>rainofsnow.com</li>
<li>raisingthedead.ninja</li>
<li>ranobes.net</li>
<li>ranobes.top</li>
<li>re-library.com</li>
<li>readcomiconline.li</li>
<li>reader-hub.com</li>
<li>readfreebooksonline.org</li>
<li>readhive.org</li>
<li>readlightnovel.cc</li>
<li>readlightnovel.me</li>
<li>readlightnovel.meme</li>
<li>readlightnovel.org</li>
<li>readlightnovel.today</li>
<li>readlitenovel.com</li>
<li>readnoveldaily.com</li>
<li>readnovelfull.com</li>
<li>readnovelfull.me</li>
<li>readnovelfull.org</li>
<li>readwebnovel.xyz</li>
<li>readwn.com</li>
<li>readwn.org</li>
<li>rebirth.online</li>
<li>reddit.com</li>
<li>royalroad.com</li>
<li>royalroadl.com</li>
<li>rtd.moe</li>
<li>rtenzo.net</li>
<li>rubymaybetranslations.com</li>
<li>scifistories.com</li>
<li>scribblehub.com</li>
<li>secondlifetranslations.com</li>
<li>semprot.com</li>
<li>sexstories.com</li>
<li>shalvationtranslations.wordpress.com</li>
<li>shanghaifantasy.com</li>
<li>shikkakutranslations.org</li>
<li>shinsori.com</li>
<li>shintranslations.com</li>
<li>shirokuns.com</li>
<li>shmtranslations.com</li>
<li>shubaow.net</li>
<li>shubaowb.com</li>
<li>shw5.cc</li>
<li>sites.google.com</li>
<li>sj.uukanshu.com</li>
<li>sjks88.com</li>
<li>skydemonorder.com</li>
<li>skythewoodtl.com</li>
<li>snowycodex.com</li>
<li>sonako.fandom.com</li>
<li>sonako.wikia.com</li>
<li>sousetsuka.com</li>
<li>soverse.com</li>
<li>spiritfanfiction.com</li>
<li>sspai.com</li>
<li>starlightstream.net</li>
<li>sto.cx</li>
<li>storiesonline.net</li>
<li>storyseedling.com</li>
<li>sweek.com</li>
<li>systemtranslation.com</li>
<li>taffygirl13.wordpress.com</li>
<li>tamagotl.com</li>
<li>taonovel.com</li>
<li>tapas.io</li>
<li>tapread.com</li>
<li>teanovel.com</li>
<li>teanovel.net</li>
<li>teenfic.net</li>
<li>thenovelbin.org</li>
<li>tigertranslations.org</li>
<li>timotxt.com</li>
<li>titannovel.net</li>
<li>tl.rulate.ru</li>
<li>tomotranslations.com</li>
<li>topnovelfull.com</li>
<li>translationchicken.com</li>
<li>travistranslations.com</li>
<li>truyenfull.vn</li>
<li>truyenyy.com</li>
<li>trxs.me</li>
<li>ultimaguil.org</li>
<li>universalnovel.com</li>
<li>unlimitednovelfailures.mangamatters.com</li>
<li>untamedalley.com</li>
<li>veratales.com</li>
<li>vipnovel.com</li>
<li>volarenovels.com</li>
<li>wanderertl130.id</li>
<li>wanderinginn.com</li>
<li>watashiwasugoidesu.com</li>
<li>wattpad.com</li>
<li>webnovel.com</li>
<li>webnovel.live</li>
<li>webnovelonline.com</li>
<li>webnovelpub.com</li>
<li>webnovelpub.pro</li>
<li>wenku8.net</li>
<li>wfxs.tw</li>
<li>whitemoonlightnovels.com</li>
<li>wnmtl.com</li>
<li>wnmtl.org</li>
<li>woopread.com</li>
<li>wordexcerpt.com</li>
<li>worldnovel.online</li>
<li>wtr-lab.com</li>
<li>wuxia-world.online</li>
<li>wuxia.blog</li>
<li>wuxia.city</li>
<li>wuxia.click</li>
<li>wuxiabee.com</li>
<li>wuxiabee.net</li>
<li>wuxiabee.org</li>
<li>wuxiafox.com</li>
<li>wuxiago.com</li>
<li>wuxiahere.com</li>
<li>wuxiahub.com</li>
<li>wuxiamtl.com</li>
<li>wuxiaone.com</li>
<li>wuxiap.com</li>
<li>wuxiapub.com</li>
<li>wuxiar.com</li>
<li>wuxiaspot.com</li>
<li>wuxiau.com</li>
<li>wuxiaworld.co</li>
<li>wuxiaworld.com</li>
<li>wuxiaworld.eu</li>
<li>wuxiaworld.live</li>
<li>wuxiaworld.online</li>
<li>wuxiaworld.site</li>
<li>wuxiaworld.world</li>
<li>wuxiazone.com</li>
<li>xbiquge.so</li>
<li>xiaoshuogui.com</li>
<li>xiaxuenovels.xyz</li>
<li>yoraikun.wordpress.com</li>
<li>yushubo.net</li>
<li>zenithnovels.com</li>
<li>zeonic-republic.net</li>
<li>zhenhunxiaoshuo.com</li>
<li>zinnovel.net</li>
<li>zirusmusings.com</li>
</ul>
</details>
  ```
  
</details>

**Comment by gamebeaker** [comment]
@Jemeni11 why did you force push?

**Comment by Jemeni11** [comment]
I thought I was meant to rebase my commit?
https://github.com/dteviot/WebToEpub/blob/d0470c7ae3e433d68c73bea46e4b3c4dcf361540/CONTRIBUTING.md?plain=1#L10

**Pull request merged**
