### PR TITLE
Create The Sweet Alpha Prince Loves Me So Much

### PR DESCRIPTION
**Pull request by XiaoMaria**

### CODE REVIEW

**Comment by dteviot** [comment]
@XiaoMaria 
I have no idea what this is supposed to be doing.

**Comment by XiaoMaria** [comment]
> @XiaoMaria I have no idea what this is supposed to be doing.

Ah Sorry I am new to this. Actually I wanted to make an epub of a novel from a site but I don't know how to do it...if u know, can u pls help me?

**Comment by dteviot** [comment]
@XiaoMaria 
Go here and read the "How to Install" section https://github.com/dteviot/WebToEpub#user-content-how-to-install

Then, 
1. In Browser, open web page with table of contents of story you want.  e.g. https://universalnovel.com/series/the-sweet-alpha-prince-loves-me-so-much/
2. Click on the WebToEpub icon on top right of broswer.
3. On page that appears, fill in details and click the "Pack Epub" button.

Note, the above table of contents is for a site that isn't currently supported by WebToEpub.

**Comment by dteviot** [comment]
@XiaoMaria 

I've added universalnovel.com to development branch.
So, I suggest you follow the "How to install from Source (for people who are not developers)" for Firefox from the readme I mentioned earlier.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://universalnovel.com/series/the-sweet-alpha-prince-loves-me-so-much/, chapters 1 &amp; 2

For my notes: 7 minutes work

**Comment by dteviot** [comment]
Closing.  No response

**Pull request closed without merging**
