### PR TITLE
Add site https://cclawtranslations.home.blog

### PR DESCRIPTION
**Pull request by Miracutor**
- Passed the unit tests using Chrome. I don't have Firefox, so I didn't check for that browser.
- Checked using eslint. No error reported.
- Tried using packed extensions on Chrome. No problem. Work as expected for CClaw Translations Parser.
- Added name to package.json and readme.md.

### CODE REVIEW

**Review by dteviot — COMMENTED** [review]
@Miracutor 

1. You don't need parserFactory.registerUrlRule, parserFactory.register should be sufficient for this site.

2. Are you sure isChapterHref() is correct?
Because I suspect code like this
```javascript
            !href.contains("facebook") ||
            !href.contains("twitter") ||
```
doesn't do what you want.
I think you're trying to say "and does not include "facebook" or "twitter"

Try
```javascript
        return (
            hostname === "cclawtranslations.home.blog" &&
            !href.contains("facebook") &&
            !href.contains("twitter") &&
            !href.contains("discord")
        );
```

But you don't need to do that either.  The call to removeUnwantedElementsFromContentElement removes them as they're inside a sharedaddy div.

3. In the removeUnwantedElementsFromContentElement, you don't need different cases.  Just use toLowerCase()
That said, "discord" might appear in an ordinary chapters.  You only want to filter in links.  See below.



4. Finally, as this is a WordPress site, you can use the WordPressBaseParser, and just tweak the bits you need.  See below.

```javascript
"use strict";

parserFactory.register(
    "cclawtranslations.home.blog",
    () => new CClawTranslationsParser()
);

class CClawTranslationsParser extends WordpressBaseParser {
    constructor() {
        super();
    }

    // title of the story  (not to be confused with title of each chapter)
    extractTitleImpl(dom) {
        const re = /( \(LN\))|( ToC)/g;
        // regex for removing ToC and (LN) from series title
        return dom.querySelector("h1.entry-title").innerText.replace(re, "");
    }

    // chapter title
    findChapterTitle(dom) {
        const re = /(\w.*)(?<=Volume \d )/g;
        // regex for removing series name from chapter title
        return dom.querySelector("h1.entry-title").innerText.replace(re, "");
    }

    removeUnwantedElementsFromContentElement(element) {
        super.removeUnwantedElementsFromContentElement(element);
        util.removeElements(
            [...element.querySelectorAll("p")].filter(this.hasDiscordOrPatreon)
        );
    }

    hasDiscordOrPatreon(p) {
        let links = [...p.querySelectorAll("a")]
            .map(l => l.href.toLowerCase())
            .filter(h => h.includes("discord") || h.includes("patreon"));
        return 0 < links.length || p.textContent.toLowerCase().includes("patreon");
    }
}
```

**Comment by dteviot** [comment]
@Miracutor 

1. You don't need parserFactory.registerUrlRule, parserFactory.register should be sufficient for this site.

2. Are you sure isChapterHref() is correct?
Because I suspect code like this
```javascript
            !href.contains("facebook") ||
            !href.contains("twitter") ||
```
doesn't do what you want.
I think you're trying to say "and does not include "facebook" or "twitter"

Try
```javascript
        return (
            hostname === "cclawtranslations.home.blog" &&
            !href.contains("facebook") &&
            !href.contains("twitter") &&
            !href.contains("discord")
        );
```

But you don't need to do that either.  The call to removeUnwantedElementsFromContentElement removes them as they're inside a sharedaddy div.

3. In the removeUnwantedElementsFromContentElement, you don't need different cases.  Just use toLowerCase()
That said, "discord" might appear in an ordinary chapters.  You only want to filter in links.  See below.



4. Finally, as this is a WordPress site, you can use the WordPressBaseParser, and just tweak the bits you need.  See below.

**Comment by dteviot** [comment]
@Miracutor 
I apologize, my manners are horrible.
Thank you very much for your contribution.  It is appreciated.
I've merged it in, and cleaned it up.  If you're interested, the commit is: https://github.com/dteviot/WebToEpub/commit/5e696cd993d930e98d801a6e6462ae8335857252

Note, this commit is on the ExperimentalTabMode branch.   That's the work in progress branch.  Master is for tracking latest release.

**Comment by Miracutor** [comment]
I don't mind. Or rather sorry and thanks for taking the time to correct my mistakes and even give me the advice to correct them.  I will make sure to do better next time for another parser!

**Pull request merged**
