### PR TITLE
Add Library Function.

### PR DESCRIPTION
**Pull request by gamebeaker**
Function mentioned in #812 it makes use of the feature "Readinglist".

Firefox error getBytesInUse() for local storage.
Bug is known https://bugzilla.mozilla.org/show_bug.cgi?id=1385832

Help needed:
UI (doesn't look nice)
"Search new Chapter" doesn't work for all websites ([www.webnovel.com](http://www.webnovel.com/))

### CODE REVIEW

**Comment by dteviot** [comment]
@gamebeaker 
Your title for the commit is horrible.
It took me some time to figure out it's implementing feature "Update downloaded epubs".

The note about getBytesInUse() is totally unclear.  Are you saying: 
1. You've fixed an existing problem that WebToEpub had on Firfox, or
2. Your new feature does not work on Firefox, or
3. Your new feature needed to work around this problem.  (From inspecting the commit, I think is your intent.)  

I'm also not exactly comfortable about how it works.
I think it's keeping a copy of the epub in the browser's local storage.  Which is not ideal.
And means I'm going to have to update the documentation about what user info WebToEpub keeps a record of.

That said, it's a requested feature, and you've clearly put a lot of effort into this.
So, how about the following.
You get @vanessabluellie to take this for a test drive (you might need to pre-build the a copy of the extension for her.)
If she tells me she's OK with it, I'll merge it in.

**Comment by gamebeaker** [comment]
@dteviot Hi i am trying to explain what the Changes are. In the Picture you can see the text "Library uses: 472 KBytes" in firefox it is alway "Library uses: 0 Bytes" because the function chrome.storage.local.getBytesInUse doesn't work.
grafik

Following i am going to explain the Buttons:
"Add to Library" : Activates the Readinglist Checkbox and Downloads the Content.
1st scenario: The "Starting URL" from the epub doesn't exist in the Library as "Story URL"
To save the Content to the Browser i used chrome.storage.local.set... wich is compatabal with firefox.
The epub is stored in the Browser with with the key "LibEpub+ID".
The Story URL is copied from Strating URL and stored with the key "LibStoryURL+ID".
Filename is copied from Filename and stored with the key "LibFilename+ID".
ID is the same number for the same epub entry.
After the epub is saved in chrome.storage the save as dialog opens.
2nd scenario: The "Starting URL" from the epub exists in the Library as "Story URL".
Content is normaly downloaded. The downloaded epub is merged with the saved epub in chrome.storage.local.
The merged epub is saved under chrome.storage.local...
The save as dialog opens with the Filename from chrome.storage.local.get("LibFilename+ID).

"Library": shows the saved epubs in chrome.storage.local... and renders the cover images or it hides the Library.


"Clear Library": Deletes the whole chrome.storage.local area with chrome.storage.local.clear().

"Delete Epub": Delets the corresponding epub, Story URL and Filename.

"Search new Chapters": Copies the Story URL in the Startig URL field and "clicks" "Load and Analyse" it also activates the Readinglist Checkbox.

"Download EPUB": Downloads the corresponding Epub.

"Coose File": Opens Upload Dialog and enabels the user to add previously downloaded epubs to the Library. After the upload the Story URL Field is empty and the user has to fill it with the right URL. The Filename is automatically the same as the uploaded File. The user has to watch out that the Readinglist is working right.

I just found a bug which breaks the images from the new epub if i merge the "old" and the "new" epub. I am going to fix it tomorrow.

@vanessabluellie i would appreciate it if you would test drive it. Here are the Files.
[Library Function.zip](https://github.com/dteviot/WebToEpub/files/10420516/Library.Function.zip)

**Comment by gamebeaker** [comment]
@vanessabluellie
Hi thank you for your feedback i appreciate it greatly. I am going to make changes to extension and post it again here for you to test. I need a few days for it as i have little time at the moment.

"The major error of this function would be that it seems that pre-existing EPUB..."
You can use pre-existing epub i am going to explain how:
1. In this example the old epub has Chapter 1 - Chapter 100.
2. Go to the website with the content like you want to download it and click on WebToEpub
3. Click on "Advanced Options" and check "Include in Reading List"
4. "Unselect All" chapter than check the last chapter from the old epub in this example Chapter 100.
5. Click "Pack Epub" and save the epub wich only has one chapter. You have to download the epub even if you delete it directly after this.
6. upload your old epub in the Library and add the Story URL
7. "Search new Chapters" now only selects the missing Chapter for your epub.
8. Click "Add to Library"
Warning: Using "Pack EPUB" and "Add to Library" on the same URL is going to set the Readinglist to a new progress.
Example: You "Add to Library" a new EPUB than if a new chapter comes out you click "Pack EPUB" instead of "Add to Library" if you now try to "Add to Library" after that it is going to say "No chapters found" or you have skipped one chapter in the Library Epub (you have to close the tab and open WebToEpub for this).

This is my intended work flow for existing epub. Maby i am going to add a merge function like you described.

"the extension was unable to automatically detect which chapters were NEW and had simply selected ALL chapters from the source's Table of Contents itself... "
The extension can't detect which chapters are new. It is using the reading list to keep track of which Chapter are new. I think the reason that you thougt with new epubs it would be working is that if you press "Add to Library" or "Search new Chapters" in "Advanced Options" the checkbox "Including in Reading List" is checked. If you press the button "View Reading List" you can delete specific URLs so that your progress is deletet. If you press "Search new Chapters" after deleting the URL from the reading list it is again checking each chapter.

"I also tested how the source link performed in conjuction with the uploaded EPUB file..."
The described working of the extension is intendet but I am going to add a warning.
The reason is that sometimes a Translator drops a novel on one site and another Translator picks it up on a different site. So you are able to create one epub for the story and you don't have to create one for each site.

"Lastly, a minor issue I picked up on was about the metadata..."
You don't have to fill out the metadata again. Only the new Chapters get merged in the saved epub from the library. That also means that if your epub in the library doesn't have metadata it isn't going to get metadata through "Add to Library". If your Epub in the Library has metadata it is going to keep it even if you didn't fill out the fields.

@vanessabluellie again thank you for your feedback.

Bugs i try to fix:
- [ ] Images get broken.
- [ ] Firefox can only download 26 Chapters befor InternalError: too much recursion. (only on some epubs?)

impovements:
- [ ] save Cover image in storage so it doesn't need to be read from the epub each time it renders. (to speed up the displaying of saved epubs)
- [ ] Warning if Story url different than original epub url.
- [ ] Create Help button for user. (with examples)

**Comment by vanessabluellie** [comment]
@gamebeaker 
Thank you so much for your explanation and I apologise for my lack of understanding. So this function is meant to be used in conjunction with the "Reading List" tool! That makes much more sense, so please do wipe away all that I had registered as errors then ahah (since the majority of them most likely were not). But again, thank you very much and no rush at all. Thank you for all the time and considerations you've invested in this! :D

**Comment by gamebeaker** [comment]
@vanessabluellie update please give it a test drive.
[library.zip](https://github.com/dteviot/WebToEpub/files/10593768/library.zip)

@dteviot i am going to create a new Pull request with the added changes if @vanessabluellie  doesn't have any complaints.
- [ ] Create Help button for user. (with examples)
- [ ] clean up code

**Comment by dteviot** [comment]
@gamebeaker 
Are you sure this has all your commits?  
I don't see any commits later than 13 January.
But maybe I'm doing it wrong.

https://github.com/dteviot/WebToEpub/compare/master...gamebeaker:WebToEpub:master

**Comment by gamebeaker** [comment]
@dteviot I haven't commited because i thougt that it wouldn't be good to have a lot of commits in a merge request. Is the number of commits in a merge request not relevant? If so i can commit the current state to my repo.

**Comment by vanessabluellie** [comment]
@gamebeaker 

Hello! Thank you for the new update, but there seems to be a different problem this time. I won't be able to test drive this at all (for the moment) because no matter what EPUB I upload and whichever button I click to test it out, an error keeps appearing...

image

I had uploaded the same EPUB to the Library that I had used in the first test drive but this error never popped up, so perhaps it may be a new issue because it seems to reoccur with every function (and button, except "Delete EPUB") now? But I'm really not sure why this is? Really sorry about this, but since I don't understand these things, maybe I'm doing something wrong?

**Comment by dteviot** [comment]
@gamebeaker 
I my opinion, a merge request should be a complete piece of work.
So please, include all the pieces.

**Comment by gamebeaker** [comment]
@vanessabluellie your second error #902. 
I can't recreate your first error. I used this story to test https://www.royalroad.com/fiction/62087/saintess-summons-skeletons
win10: firefox 109.0.1
win10: chrome 109.0.5414.120
Fedora Linux 37: firefox 109.0.1
Fedora Linux 37: chrome 109.0.5414.117
My System is 64-Bit.
Can you please share the link for your test story.
What is your system?

**Comment by vanessabluellie** [comment]
@gamebeaker 

My system is Windows 11, Chrome Browser, 64-bit.

I used an old epub file from one of the parsers already working with WebToEpub (and uploaded it into the Library):
https://peachblossomcodex.com/novel/bsdtwtbav/

Your first version I had tested didn't actually have these errors and only needed to be polished, so that's why I was little confused with the second version when all buttons I tried using kept popping up with this error. Perhaps I'm missing something...?

**Comment by gamebeaker** [comment]
@vanessabluellie Can you please upload your Ebup which causes errors here https://mega.nz/filerequest/CIyoAHhUsVs

"Ah and lastly, I tried using the button "Add chapter from different EPUB", which has an amazing merge functionality!, but so far, it..."
What you describe should be possible. Did you try to append the Epub wich causes the error if you upload it or another which doesn't cause an error?

- [ ] Create Help button for user. (with examples)
- [ ] EPUB 3 compatible
- [ ] check if it works with different options en/disabled
- [ ] more metadata
- [ ] clean up code

**Comment by vanessabluellie** [comment]
@gamebeaker 

The EPUB I used was random and the same as the first test drive (I uploaded it to mega as requested)! Please let me know if you had not received it, I labelled the file as "WebToEPub Error (File is Corrupt)".

`What you describe should be possible. Did you try to append the Epub wich causes the error if you upload it or another which doesn't cause an error?`

For this, I firstly tried using the same EPUB with that error and then appended another EPUB to it (from the exact same source) and it worked by merging the files together. Then I tried merging a completely different EPUB from another source to that EPUB with the error and nothing happened... I also tried merging another EPUB from the same website, but not the exact same link (i.e. from a **different novel** on the site) but this also didn't work...

**Comment by gamebeaker** [comment]
@dteviot i have a question about "Create EPUB 3" in Advanced Options. Does it only create a "toc.xhtml" file and nothing more or does it enable WebToEpub to download embed Videos and Audios in Chapters? In EpubPacker.js in line 7 is a comment "For our purposes, an EPUB only contains two types of content file: XHTML and image."

**Comment by dteviot** [comment]
@gamebeaker,
IIRC creating an EPUB 3 just adds a toc.xhtml file.
At time, I thought EPUB 3 spec allowed HTML 5 files for content.  
But it doesn't.  It still requires XHTML.  (Basically, providing the EPUB 3 file generation in WebToEpub was a waste of time.)

**Comment by gamebeaker** [comment]
@dteviot i just edited your wiki page a lot of the stuff was copied from your original wiki. It looks like it is live and not a pull request...
I didn't know a few options:
https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#use-svg-for-images
https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#reset
https://github.com/dteviot/WebToEpub/wiki/Advanced-Options#automatic-parser-select-includes-baka-tsuki-series-page-parser

**Comment by dteviot** [comment]
@gamebeaker 
Thank you for your hard work

**Comment by gamebeaker** [comment]
@dteviot As a warning I couldn't recreate the latest bugs @vanessabluellie described even with the uploaded EPUB :/. (corrupted zip, appended another EPUB)

**Comment by dteviot** [comment]
Noted.

**Pull request merged**
